package Math;
//https://leetcode.com/problems/xor-operation-in-an-array/description/
// time complexity: O(n)
// space complexity: O(1)
// approach: we can simply iterate through the array and xor all the elements of the array. The array is generated by the formula: nums[i] = start + 2*i where i is the index of the array. We can start with the first element of the array which is start and then xor it with the next elements of the array which are generated by the formula. Finally, we will get the xor of all the elements of the array.
// technique used: math
class XorOperationInAnArray {
    public int xorOperation(int n, int start) {
        int xor=start;
        for(int i=1;i<n;i++)
        {
            xor^=start+2*i;
        }
        return xor;
    }
}